---
- name: Create F5 LTM VIP and Pool with Client SSL
  hosts: all
  connection: local
  gather_facts: false
<<<<<<< HEAD
  collections:
    - f5networks.f5_modules
=======

  collections:
    - f5networks.f5_modules

>>>>>>> ff3166e (	new file:   Ansible_F5_Automation_Demo_Kailas_Pathade.docx)
  vars:
    f5_provider:
      server: "{{ ansible_host }}"
      user: "{{ f5_username }}"
      password: "{{ f5_password }}"
      validate_certs: false
<<<<<<< HEAD
  tasks:
=======

  tasks:

>>>>>>> ff3166e (	new file:   Ansible_F5_Automation_Demo_Kailas_Pathade.docx)
    - name: Show F5 connection information
      ansible.builtin.debug:
        msg:
          - "Inventory host: {{ inventory_hostname }}"
          - "F5 management IP: {{ ansible_host }}"
<<<<<<< HEAD
=======

>>>>>>> ff3166e (	new file:   Ansible_F5_Automation_Demo_Kailas_Pathade.docx)
    - name: Create HTTPS health monitor
      f5networks.f5_modules.bigip_monitor_https:
        name: MON_APP01
        provider: "{{ f5_provider }}"
<<<<<<< HEAD
        send: GET /
        receive: HTTP
        interval: 5
        timeout: 16
        state: present
=======
        send: "GET /"
        receive: "HTTP"
        interval: 5
        timeout: 16
        state: present

>>>>>>> ff3166e (	new file:   Ansible_F5_Automation_Demo_Kailas_Pathade.docx)
    - name: Create Client SSL profile
      f5networks.f5_modules.bigip_profile_client_ssl:
        name: CLIENTSSL_APP01
        cert_key_chain:
<<<<<<< HEAD
          - cert: default.crt
            key: default.key
        provider: "{{ f5_provider }}"
        state: present
    - name: Create Server SSL profile
      f5networks.f5_modules.bigip_profile_server_ssl:
        name: SERVERSSL_APP01
        parent: serverssl
        provider: "{{ f5_provider }}"
        state: present
=======
          - cert: clientssl.crt
            key: clientssl.key
        provider: "{{ f5_provider }}"
        state: present

>>>>>>> ff3166e (	new file:   Ansible_F5_Automation_Demo_Kailas_Pathade.docx)
    - name: Create F5 pool
      f5networks.f5_modules.bigip_pool:
        name: POOL_APP01
        lb_method: round-robin
        monitors:
          - MON_APP01
        provider: "{{ f5_provider }}"
        state: present
<<<<<<< HEAD
=======

>>>>>>> ff3166e (	new file:   Ansible_F5_Automation_Demo_Kailas_Pathade.docx)
    - name: Add pool member 1
      f5networks.f5_modules.bigip_pool_member:
        pool: POOL_APP01
        name: APP01_MEMBER_1
        host: 10.10.10.11
<<<<<<< HEAD
        port: "443"
        provider: "{{ f5_provider }}"
        state: present
=======
        port: 443
        provider: "{{ f5_provider }}"
        state: present

>>>>>>> ff3166e (	new file:   Ansible_F5_Automation_Demo_Kailas_Pathade.docx)
    - name: Add pool member 2
      f5networks.f5_modules.bigip_pool_member:
        pool: POOL_APP01
        name: APP01_MEMBER_2
        host: 10.10.10.12
<<<<<<< HEAD
        port: "443"
        provider: "{{ f5_provider }}"
        state: present
=======
        port: 443
        provider: "{{ f5_provider }}"
        state: present

>>>>>>> ff3166e (	new file:   Ansible_F5_Automation_Demo_Kailas_Pathade.docx)
    - name: Create virtual server
      f5networks.f5_modules.bigip_virtual_server:
        name: VIP_APP01_HTTPS
        destination: 192.168.1.200
<<<<<<< HEAD
        port: "443"
        pool: POOL_APP01
        ip_protocol: tcp
        snat: Automap
        default_persistence_profile: /Common/cookie
        profiles:
          - http
          - CLIENTSSL_APP01
          - SERVERSSL_APP01
        irules: Insert_XFF
        provider: "{{ f5_provider }}"
        state: present

=======
        port: 443
        pool: POOL_APP01
        ip_protocol: tcp
        profiles:
          - http
          - CLIENTSSL_APP01
        provider: "{{ f5_provider }}"
        state: present
>>>>>>> ff3166e (	new file:   Ansible_F5_Automation_Demo_Kailas_Pathade.docx)
